#PBS -N tqqr-s2-sample2
#PBS -l select=4:ncpus=16:model=san
#PBS -l walltime=61:00:00
#PBS -V
#PBS -mabe -M8312398965@msg.fi.google.com
#PBS -r n

cd $PBS_O_WORKDIR

# If using matlab uncomment next line and use pfe number
#ssh -4 -fN -L 1700:localhost:1700 -L 1702:localhost:1702 -L 1703:localhost:1703 pfe##

# Example using anaconda python
. /home1/nmovshov/miniconda3/etc/profile.d/conda.sh
conda activate
mpirun -n 64 python tripquad_quartop.py >& rlog.log

